appName: bae-career-ui
imageName: ymandrews/bae-careers-ui:0.1.2
replicas: 1
serviceName: bae-career-ui-svc
targetPort: 3000
sourcePort: 3000
nodePort: 32760
appVersion: 0.1.2
careersRestApiUrl: http://10.104.155.141:30003/jobs

